// <auto-generated />
using System;
using Discount.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountDbContext))]
    partial class DiscountDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Discount.Grpc.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10,
                            IsPercentage = true,
                            ProductId = new Guid("019818ea-8772-4018-b80e-299a71c88593")
                        },
                        new
                        {
                            Id = 2,
                            Amount = 49,
                            IsPercentage = false,
                            ProductId = new Guid("019818ed-1b45-4d55-bdca-2af7a00883ff")
                        },
                        new
                        {
                            Id = 3,
                            Amount = 129,
                            Description = "Special coupon that can only be used once",
                            IsPercentage = false,
                            ProductId = new Guid("5334c996-8457-4cf0-815c-ed2b77c4ff61")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
