services:
  catalog.db:
    container_name: catalog.db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=catalog.db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres.catalog:/var/lib/postgresql/data/